### ISSUE TITLE
没有题目不知道什么意思

### ISSUE THREAD

**Issue by lanweipeng** [txu1/blog#32]
只有代码，题目都没有，向compose，curry我就看不懂

**Comment by txu1** [comment]
这都是面向函数编程的概念，同时也是Loadash/Underscore函数工具库里的方法，compose是组合函数，curry是柯里化函数，还有很多参数和返回值都是函数的方法，像防抖、节流、偏函数、惰性函数、记忆函数

function func1(x){}
function func2(x){}
function func3(x){}
compose(func1, func2, func3) (x) === func1(func2(func3(x)))

function func4(x, y, z){
  console.log(x, y, z)
}
curry(func4)(x)(y)(z) === func4(x, y, z)
