### ISSUE TITLE
flattern代码错误

### ISSUE THREAD

**Issue by lanweipeng** [txu1/blog#35]
function Flatten(arr) {
    var res = [];
    for (var i = 0, len = arr.length; i < len; i++) {
        if(Array.isArray(arr[i])) res = res.concat(flatten(arr[i]))//flatten和Flatter不一样，程序运行报错
        else res.push(arr[i])
    }
    return res;
}

**Comment by txu1** [comment]
> function Flatten(arr) {
> var res = [];
> for (var i = 0, len = arr.length; i < len; i++) {
> if(Array.isArray(arr[i])) res = res.concat(flatten(arr[i]))//flatten和Flatter不一样，程序运行报错
> else res.push(arr[i])
> }
> return res;
> }

感谢指出
